version: '3'
services:
  client:
    build: client
    restart: always
    image: port-of-mars/client/dev:latest
    volumes:
      - ./client:/code
      - /code/node_modules
    command: './dev.sh'
    ports:
      - '8081:8080'
  server:
    command: './dev.sh'
    ports:
      - '3006:3005'